### PR TITLE
Log errors and fail the build

### PR DESCRIPTION
**Pull request by joshaber**
(This should be upstreamed at some point, just trying to nail down what's going on with Windows builds currently.)

### CODE REVIEW

**Comment by joshaber** [comment]
(And CI is expected to fail, given that we're not on a tag.)

**Comment by maxkorp** [comment]
I 100% did not see that this was a PR before making/merging #4 >.<

**Comment by maxkorp** [comment]
Agreed re-upstreaming most of it.

**Comment by johnhaley81** [comment]
It looks like all of this is in master. Should we close this out?

**Comment by joshaber** [comment]
Yup :+1:

**Pull request closed without merging**
